version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    environment:
      JWT_KEY: secret
      MONGO_URI: mongodb://mongo:27017/booworld
  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017"
    restart: always
    volumes:
      - booworld_mongo:/data/db/

volumes:
  booworld_mongo: